import localFont from "next/font/local";
import "./globals.css";

const nefelibata = localFont({
  src: "./fonts/Nefelibata-Script.ttf",
  variable: "--font-nefelibata",
});

const quicksand = localFont({
  src: "./fonts/Quicksand.ttf",
  variable: "--font-quicksand",
});

export const metadata = {
  title: "Yas & Juampi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${nefelibata.variable} ${quicksand.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
